# Generated by Django 5.1.1 on 2024-10-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_number', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('payment', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('featured_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.featured')),
            ],
        ),
    ]
