# Generated by Django 5.1.1 on 2024-10-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
    ]
