# Generated by Django 5.1.1 on 2024-10-22 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_invoice',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
