# Generated by Django 5.1.1 on 2024-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_client_invoice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_invoice',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
